name: pesuacademy
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - appdirs==1.4.4
      - beautifulsoup4==4.12.3
      - bs4==0.0.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - cssselect==1.2.0
      - fake-useragent==1.5.1
      - idna==3.7
      - importlib-metadata==7.1.0
      - lxml==5.2.1
      - lxml-html-clean==0.1.1
      - parse==1.20.1
      - pyee==11.1.0
      - pyppeteer==2.0.0
      - pyquery==2.0.0
      - requests==2.31.0
      - requests-html==0.10.0
      - soupsieve==2.5
      - tqdm==4.66.2
      - typing-extensions==4.11.0
      - urllib3==1.26.18
      - w3lib==2.1.2
      - websockets==10.4
      - zipp==3.18.1
prefix: /home/aditeyabaral/miniconda3/envs/pesuacademy
